### PR TITLE
[FEI-3165] Use GITHUB_ENV

### PR DESCRIPTION
**Pull request by somewhatabstract**
This upadtes our environment variables to use the GITHUB_ENV file instead of the deprecated ::set-env

## Summary:

Issue: FEI-3165

## Test plan:
Push this PR and see if the actions properly execute and update the branch with
build artifacts.

### CODE REVIEW

**Comment by somewhatabstract** [comment]
Looks like I need to update the SSH action.

**Review by jeresig — APPROVED** [review]
Nice! That's pretty straightforward, thank you!

**Review by kevinbarabash — APPROVED** [review]
I'm glad the fix was straight forward.  How are secrets accessed once they're in `$GITHUB_ENV`?

**Comment by somewhatabstract** [comment]
> I'm glad the fix was straight forward. How are secrets accessed once they're in `$GITHUB_ENV`?

I don't know what that question means.

**Pull request merged**
